[package]
name = "resultbot"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
tokio = { version = "1.39.3", features = ["full"] }
reqwest = "0.11"
fantoccini = "0.21.1"
serde = "1.0.28"
serde_json = "1.0.25"
